### PR TITLE
update database doc

### LINKED ISSUE #33: Create database docs
Add database image to `docs/database/database.png`

### PR DESCRIPTION
**Pull request by trandaison**
I added the database image. Please review and merge this one.
Fix #33

### CODE REVIEW

**Comment by ghost** [comment]
Please the following points: 
- All table name and column name should be in lower case and `under_score` style
- Add some information for users table : birthday, sex, address ...
- `staff_id` should not be used in `orders` and `bills` table, use `user_id` instead
- what is the `payment_id` in `bill_details` table ?
- number columns like `total_cost`, `remaining_amount`, `amount` should have the default value.

**Comment by trandaison** [comment]
@at-vienlm 
I fixed all of your comments, please review and merge this one.

**Comment by ghost** [comment]
@at-sontd I don't see you fix. 
- number columns like total_cost, remaining_amount, amount should have the default value.
- what is the payment_id in bill_details table ?
- staff_id should not be used in orders and bills table, use user_id instead

**Comment by trandaison** [comment]
@at-vienlm 
I fixed all your comments, please review and merge this one. Thank you.

**Comment by ghost** [comment]
:+ LGTM.

**Pull request merged**
